name: Build Docs

on:
  push:
    paths: ['stories/**', 'apps/**', 'components/**', 'utils/**']
    branches: [master]
  workflow_dispatch:

jobs:
  buildDocs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Bootstrap if cached
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: lerna bootstrap
      - run: npm run lint
      - run: npm test
      - run: npm run deploy-docs
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: 'docs'
          author_name: GitHub Actions
          author_email: actions@github.com
          branch: master
          message: Updating github docs
