name: Testing

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache node modules and Cypress
        id: cache-node-modules-cypress
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-cypress
        with:
          path: node_modules
            /home/runner/.cache/Cypress
          key: ${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules-cypress.outputs.cache-hit != 'true'
        run: npm ci

      - name: Bootstrap if cached
        if: steps.cache-node-modules-cypress.outputs.cache-hit == 'true'
        run: lerna bootstrap

      - run: npm run lint
      - run: npm test
