name: Testing

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        id: git-diff
        with:
          PATTERNS: |
            +components/**/*.*
            +utils/**/*.*
            +apps/**/*.*

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache node modules and Cypress
        id: cache-node-modules-cypress
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-cypress
        with:
          path: node_modules
            /home/runner/.cache/Cypress
          key: ${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules-cypress.outputs.cache-hit != 'true'
        run: npm ci

      - name: GIT DIFF
        run: echo ${{ env.GIT_DIFF }}

      - name: GIT DIFF_VALUES
        run: echo ${{ steps.git-diff.outputs.diff }}

      - name: Bootstrap if cached
        if: steps.cache-node-modules-cypress.outputs.cache-hit == 'true'
        run: lerna bootstrap

      - run: npm run lint
      - run: npm test

      - name: Build Docs
        run: npm run build-docs
        if: env.GIT_DIFF

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: 'docs'
          message: 'docs: Rebuilding docs'
        if: env.GIT_DIFF
